### ISSUE TITLE
[Refactoring] Use Retrofit instead of XMLPullParser

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FoodForYou#47]
**Code review :** 
 use retrofit so you don't have to worry about thread management as it becomes hard to maintain

**What I should do :** 
Change XMLPullParser to Retrofit 
- Retrofit doesn't support XMLPullParser convertor but it supports SimpleXml.
  So, I should investigate about SimpleXml convertor.

**Comment by SeulGeek** [comment]
> Deprecated – Please switch to the JAXB Converter
The Simple XML project is no longer maintained. We recommend switching to the JAXB converter.
Ref: https://github.com/square/retrofit/tree/master/retrofit-converters/simplexml

I tried several times using Retrofit for refactoring but failed. And I found above information in public retrofit readme file.
The reason what I failed is that SimpleXml converter was depreciated. So, I checked another way that is using JAXB Coverter.
But in android, it can't use.. :(

> Note that JAXB does not work on Android.
Ref: https://github.com/square/retrofit/tree/master/retrofit-converters/jaxb


<ins>**_So, I decided to keep XmlPullParser library because there's no alternative._** </ins>


Etc. 
Simple을 사용하여 XML 직렬화하기
https://webprogrammer.tistory.com/2066

To Parse or Not to Parse XML on Android in 2019
https://infinum.com/the-capsized-eight/to-parse-or-not-to-parse-xml-on-android-in-2019

**Comment by SeulGeek** [comment]
@EldredRoer hi, please read above comment. And If you have any good ideas, feel free to talk to me. If there are no issues, let me close this ticket. Thank you :)

**Comment by EldredRoer** [comment]
hmmm yeah makes sense. Not many people use legacy code these days :)

Ok, close ticket please.
