### ISSUE TITLE
[Security Issue] Minified enabled in grade should be true not false

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FoodForYou#48]
- Change minifyEnabled status to true for security

Ref.
- Shrink, obfuscate, and optimize your app: https://developer.android.com/studio/build/shrink-code#shrink-resources

**Comment by SeulGeek** [comment]
@EldredRoer If I miss something, please let me know. thank you :)

**Comment by EldredRoer** [comment]
Looks good 👍
