### ISSUE TITLE
[Refactoring] Rename variable according to android standard

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FoodForYou#49]
The variable names are not according to android standard. So, change it.

ex) If it is global variable, it should be start "m". like mDietMainCategory

**Comment by SeulGeek** [comment]
done! @EldredRoer could you please review this when you have time?
If I miss or wrong something, please let me know. Thank you always! 😄

**Comment by EldredRoer** [comment]
Looks good. Awesome job :)
