### ISSUE TITLE
Add the latest buildToolsVersion

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FoodForYou#50]
Android SDK Build-Tools is a component of the Android SDK required for building Android apps. You should always keep your Build Tools component updated by downloading the latest version using the Android SDK Manager. 

- requirement: update the latest buildToolsVersion (30.0.2)

Ref. https://developer.android.com/studio/releases/build-tools

**Comment by SeulGeek** [comment]
@EldredRoer Please check this when you have time. Thank you! :)

**Comment by EldredRoer** [comment]
Please refer to this official stable release. Best to use 29.0.3 as its recent stable version :)

https://developer.android.com/studio/releases/build-tools

**Comment by SeulGeek** [comment]
updated! thank you! :) 👍
