### ISSUE TITLE
Check null when calling getIntent

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FoodForYou#51]
- Check null when calling getIntent

**Comment by SeulGeek** [comment]
@EldredRoer Is it needed to check null for each case?

**AS-IS**
![image](https://user-images.githubusercontent.com/64777031/101039204-2292be00-35bf-11eb-81fd-3a2a1550dccc.png)

**TO-BE** (example)
![image](https://user-images.githubusercontent.com/64777031/101039736-4524d700-35bf-11eb-8705-4d558f688189.png)

And I will change hard coding like this
ex)
![image](https://user-images.githubusercontent.com/64777031/101040606-874e1880-35bf-11eb-9334-0a50e97b1f6c.png)
![image](https://user-images.githubusercontent.com/64777031/101040773-9208ad80-35bf-11eb-9c29-a56a52d95830.png)

**Comment by EldredRoer** [comment]
Good Q.

Yes we should aways check for null however in this case, checking one by one is too lengthy so best practice is to have one null check depending on what you plan for in the logic. Something like this

```
if(getIntent() == null) {
return; 
}
```

**Comment by SeulGeek** [comment]
yeah that is more simple way :D Thank you I've updated it! 👍
